### ISSUE TITLE
Question about score penalty

### ISSUE THREAD

**Issue by buttercutter** [bismex/RLT-DIMP#1]
How does this new [score penalty](https://arxiv.org/pdf/2008.04722.pdf#page=7) works ?

1. Why "This temporal constraint allows objects to be detected at relatively far locations." ?
2. Why multiply by the previous score penalty, Snew ?

![rlt-dimp_score_penalty](https://user-images.githubusercontent.com/3324659/95197404-23e87a00-080c-11eb-8ca6-17db316d5f3b.png)

**Comment by bismex** [comment]
The reliability score for the newly estimated object controls future object tracking results. If the reliability score is low, tracking does not proceed with the object, and if the score is high, the object tracker trusts the newly estimated object and proceeds to track. Therefore, this reliability score must be carefully handled in tracking objects, especially for robust tracking.

As suggested in the paper, when an object at a long distance is similar to the original object tracking object, the object has a high-reliability score, and a problem occurs that the object is incorrectly tracked as a new object instead of the original object. To prevent this, a spatial penalty is applied to the score in consideration of the previous object tracking position and the newly estimated object tracking position. The larger the distance difference, the lower the score.

However, if the confidence score continues to be measured low due to the presence of a spatial penalty, it may not be possible to properly track the object even though the original object has newly appeared. In particular, the original object may appear at a distance from the original location. Therefore, we add a temporal penalty term to attenuate the spatial penalty. We will answer your questions based on this background knowledge.

1) As can be seen from the equation, if the difference between t_new and t_old increases (ie, the period of not finding an object increases), the penalty for distance is attenuated and the confidence score increases.

2) This equation has nothing to do with the previous score penalty (s_old), and it is an equation that multiplies the score (s_new) of the current frame by the penalty weight.

**Comment by buttercutter** [comment]
What is the difference between `S'new` and `Snew` ?

**Comment by bismex** [comment]
s_new: confience score for present frame
s_new' : confidence score modified by the spatio-temporal penalty for present frame
